import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SectionWrapper from "@/components/SectionWrapper";
import AnalyticsCards from "@/components/AnalyticsCards";
import VehiclesPerHourChart from "@/components/VehiclesPerHourChart";
import SlotUsagePieChart from "@/components/SlotUsagePieChart";
import { Separator } from "@/components/ui/separator";
import { BarChart } from "lucide-react";

import { useQuery } from "@tanstack/react-query";
import { fetchDashboardStats, fetchDetailedAnalytics } from "@/api/api";
import { Loader2 } from "lucide-react";

const AdminAnalytics = () => {
  // Fetch basic stats
  const { data: stats, isLoading: isLoadingStats } = useQuery({
    queryKey: ['adminStats'],
    queryFn: fetchDashboardStats,
    refetchInterval: 10000,
  });

  // Fetch detailed analytics (charts)
  const { data: detailedAnalytics, isLoading: isLoadingDetailed } = useQuery({
    queryKey: ['adminDetailedAnalytics'],
    queryFn: fetchDetailedAnalytics,
    refetchInterval: 15000,
  });

  const isLoading = isLoadingStats || isLoadingDetailed;

  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-grow">
        <SectionWrapper id="admin-analytics" title="Parking Analytics" className="bg-transparent">
          <div className="max-w-3xl mx-auto text-center mb-10">
            <p className="text-lg text-muted-foreground leading-relaxed">
              Gain real-time insights into parking trends, revenue generation, and slot utilization to optimize your operations.
            </p>
          </div>

          {isLoading ? (
            <div className="flex justify-center items-center h-64">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
          ) : (
            <>
              {/* 1. Key Metrics Cards */}
              <h3 className="text-2xl font-semibold mb-4">Key Performance Indicators</h3>
              <AnalyticsCards stats={stats} detailedStats={detailedAnalytics} />

              <Separator className="my-10" />

              {/* 2. Charts Section */}
              <h3 className="text-2xl font-semibold mb-6 flex items-center space-x-2">
                <BarChart className="h-6 w-6 text-primary" />
                <span>Detailed Usage Charts</span>
              </h3>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <VehiclesPerHourChart data={detailedAnalytics?.hourlyData} />
                <SlotUsagePieChart data={detailedAnalytics?.slotDistribution} />
              </div>

              <Separator className="my-10" />

              {/* 3. Data Notes */}
              <div className="text-center p-6 bg-white dark:bg-card rounded-lg shadow-inner">
                <p className="text-sm text-muted-foreground">
                  Note: All analytics data is automatically generated by the SmartLot system sensors and ticketing logs.
                  This information is crucial for optimizing slot allocation, predicting peak congestion, and ensuring maximum operational efficiency.
                </p>
              </div>
            </>
          )}

        </SectionWrapper>
      </main>
      <Footer />
    </div>
  );
};

export default AdminAnalytics;